name: Docker image arm github CI

on:
  push: 
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:   
    runs-on: self-hosted
    steps:
      - 
        name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./    
      -
        name: Checkout Overleaf
        uses: actions/checkout@v4
        with:
          repository: "overleaf/overleaf"
          ref: ${{ matrix.versions.sha }}
          path: "${{ github.workspace }}"        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Change OVERLEAF_BASE_TAG
        working-directory: ${{ github.workspace }}
        run: |
          sed -Ei 's|sharelatex/sharelatex-base:latest|\"${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-base:latest\"|' server-ce/Dockerfile
      -
        name: Build and push image arm64
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          context: ${{ github.workspace }}
          file: server-ce/Dockerfile
          build-args: |
            SHARELATEX_BASE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:cache-latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:cache-latest,mode=max
