name: Docker Image github CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            architecture: arm64
    runs-on: ${{ matrix.runs-on }}

    steps:
      -
        name: Checkout Overleaf
        uses: actions/checkout@v4
        with:
          repository: "overleaf/overleaf"
          ref: "710cacad2dc8921e1fcfd306c54843266226be89"
          path: "${{ github.workspace }}"        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.architecture }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.architecture }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/${{ matrix.architecture }}
          context: ${{ github.workspace }}
          file: server-ce/Dockerfile
          build-args: SHARELATEX_BASE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:latest
