name: Docker baseImage github CI

on:
  push:
    branches: [main]
    paths:
      - 'sharelatex.json'  

jobs:
  prep-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: prepare
        uses: ActionsTools/read-json-action@main
        with:
          file_path: 'sharelatex.json'
    outputs:
      versions: ${{steps.prepare.outputs.versions}}

  build:
    needs: prep-env 
    strategy:
      matrix:
        versions: ${{fromJson(needs.prep-env.outputs.versions)}}      
    runs-on: ARM64

    steps:
      - 
        name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./    
      -
        name: Checkout Overleaf
        uses: actions/checkout@v4
        with:
          repository: "overleaf/overleaf"
          ref: ${{ matrix.versions.sha }}
          path: "${{ github.workspace }}"        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Change OVERLEAF_BASE_TAG
        if: ${{ inputs.buildImage }}
        working-directory: ${{ github.workspace }}
        run: |
          sed -Ei 's|sharelatex/sharelatex-base:latest|\"${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-base:${{matrix.versions.tag}}\"|' server-ce/Dockerfile
      -
        name: Build and push image arm64
        if: ${{ inputs.buildImage }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          context: ${{ github.workspace }}
          file: server-ce/Dockerfile
          build-args: |
            SHARELATEX_BASE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:${{matrix.versions.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sharelatex:${{matrix.versions.tag}}
